/// Flutter icons eye_icon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  eye_icon
///      fonts:
///       - asset: fonts/eye_icon.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class EyeIcon {
  EyeIcon._();

  static const _kFontFam = 'eye_icon';
  static const _kFontPkg = '';

  static const IconData eye =
      IconData(0xf06e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash =
      IconData(0xf070, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
